CREATE TABLE discos(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    artista VARCHAR(255) NOT NULL,
    precio DECIMAL(9,2) NOT NULL,
    genero VARCHAR(100) NOT NULL
);

CREATE TABLE artistas( 
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(255) NOT NULL, 
 nacionalidad VARCHAR(255) NOT NULL 
 );